// +build !ignore_autogenerated

/*
Copyright 2021 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaderElectionConfig) DeepCopyInto(out *LeaderElectionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaderElectionConfig.
func (in *LeaderElectionConfig) DeepCopy() *LeaderElectionConfig {
	if in == nil {
		return nil
	}
	out := new(LeaderElectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchLimitSelector) DeepCopyInto(out *MatchLimitSelector) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceRegex != nil {
		in, out := &in.NamespaceRegex, &out.NamespaceRegex
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchLimitSelector.
func (in *MatchLimitSelector) DeepCopy() *MatchLimitSelector {
	if in == nil {
		return nil
	}
	out := new(MatchLimitSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualOperator) DeepCopyInto(out *VirtualOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualOperator.
func (in *VirtualOperator) DeepCopy() *VirtualOperator {
	if in == nil {
		return nil
	}
	out := new(VirtualOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualOperatorConfiguration) DeepCopyInto(out *VirtualOperatorConfiguration) {
	*out = *in
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(VirtualOperatorControllerConfiguration)
		**out = **in
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(VirtualOperatorWebhookConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualOperatorConfiguration.
func (in *VirtualOperatorConfiguration) DeepCopy() *VirtualOperatorConfiguration {
	if in == nil {
		return nil
	}
	out := new(VirtualOperatorConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualOperatorControllerConfiguration) DeepCopyInto(out *VirtualOperatorControllerConfiguration) {
	*out = *in
	out.LeaderElection = in.LeaderElection
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualOperatorControllerConfiguration.
func (in *VirtualOperatorControllerConfiguration) DeepCopy() *VirtualOperatorControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(VirtualOperatorControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualOperatorList) DeepCopyInto(out *VirtualOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualOperatorList.
func (in *VirtualOperatorList) DeepCopy() *VirtualOperatorList {
	if in == nil {
		return nil
	}
	out := new(VirtualOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualOperatorRoute) DeepCopyInto(out *VirtualOperatorRoute) {
	*out = *in
	if in.GlobalLimits != nil {
		in, out := &in.GlobalLimits, &out.GlobalLimits
		*out = make([]MatchLimitSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubRules != nil {
		in, out := &in.SubRules, &out.SubRules
		*out = make([]VirtualOperatorRouteSubRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualOperatorRoute.
func (in *VirtualOperatorRoute) DeepCopy() *VirtualOperatorRoute {
	if in == nil {
		return nil
	}
	out := new(VirtualOperatorRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualOperatorRouteSubRule) DeepCopyInto(out *VirtualOperatorRouteSubRule) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = make([]MatchLimitSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualOperatorRouteSubRule.
func (in *VirtualOperatorRouteSubRule) DeepCopy() *VirtualOperatorRouteSubRule {
	if in == nil {
		return nil
	}
	out := new(VirtualOperatorRouteSubRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualOperatorSpec) DeepCopyInto(out *VirtualOperatorSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.Configuration.DeepCopyInto(&out.Configuration)
	in.Route.DeepCopyInto(&out.Route)
	if in.Subsets != nil {
		in, out := &in.Subsets, &out.Subsets
		*out = make([]VirtualOperatorSubset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualOperatorSpec.
func (in *VirtualOperatorSpec) DeepCopy() *VirtualOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualOperatorStatus) DeepCopyInto(out *VirtualOperatorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualOperatorStatus.
func (in *VirtualOperatorStatus) DeepCopy() *VirtualOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualOperatorSubset) DeepCopyInto(out *VirtualOperatorSubset) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RouteRules != nil {
		in, out := &in.RouteRules, &out.RouteRules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualOperatorSubset.
func (in *VirtualOperatorSubset) DeepCopy() *VirtualOperatorSubset {
	if in == nil {
		return nil
	}
	out := new(VirtualOperatorSubset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualOperatorWebhookConfiguration) DeepCopyInto(out *VirtualOperatorWebhookConfiguration) {
	*out = *in
	if in.MutatingConfigurations != nil {
		in, out := &in.MutatingConfigurations, &out.MutatingConfigurations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ValidatingConfigurations != nil {
		in, out := &in.ValidatingConfigurations, &out.ValidatingConfigurations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualOperatorWebhookConfiguration.
func (in *VirtualOperatorWebhookConfiguration) DeepCopy() *VirtualOperatorWebhookConfiguration {
	if in == nil {
		return nil
	}
	out := new(VirtualOperatorWebhookConfiguration)
	in.DeepCopyInto(out)
	return out
}
