/*
Copyright 2021 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/openkruise/kruise/apis/ctrlmesh/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVirtualOperators implements VirtualOperatorInterface
type FakeVirtualOperators struct {
	Fake *FakeCtrlmeshV1alpha1
	ns   string
}

var virtualoperatorsResource = schema.GroupVersionResource{Group: "ctrlmesh.kruise.io", Version: "v1alpha1", Resource: "virtualoperators"}

var virtualoperatorsKind = schema.GroupVersionKind{Group: "ctrlmesh.kruise.io", Version: "v1alpha1", Kind: "VirtualOperator"}

// Get takes name of the virtualOperator, and returns the corresponding virtualOperator object, and an error if there is any.
func (c *FakeVirtualOperators) Get(name string, options v1.GetOptions) (result *v1alpha1.VirtualOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(virtualoperatorsResource, c.ns, name), &v1alpha1.VirtualOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualOperator), err
}

// List takes label and field selectors, and returns the list of VirtualOperators that match those selectors.
func (c *FakeVirtualOperators) List(opts v1.ListOptions) (result *v1alpha1.VirtualOperatorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(virtualoperatorsResource, virtualoperatorsKind, c.ns, opts), &v1alpha1.VirtualOperatorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VirtualOperatorList{ListMeta: obj.(*v1alpha1.VirtualOperatorList).ListMeta}
	for _, item := range obj.(*v1alpha1.VirtualOperatorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested virtualOperators.
func (c *FakeVirtualOperators) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(virtualoperatorsResource, c.ns, opts))

}

// Create takes the representation of a virtualOperator and creates it.  Returns the server's representation of the virtualOperator, and an error, if there is any.
func (c *FakeVirtualOperators) Create(virtualOperator *v1alpha1.VirtualOperator) (result *v1alpha1.VirtualOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(virtualoperatorsResource, c.ns, virtualOperator), &v1alpha1.VirtualOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualOperator), err
}

// Update takes the representation of a virtualOperator and updates it. Returns the server's representation of the virtualOperator, and an error, if there is any.
func (c *FakeVirtualOperators) Update(virtualOperator *v1alpha1.VirtualOperator) (result *v1alpha1.VirtualOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(virtualoperatorsResource, c.ns, virtualOperator), &v1alpha1.VirtualOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualOperator), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVirtualOperators) UpdateStatus(virtualOperator *v1alpha1.VirtualOperator) (*v1alpha1.VirtualOperator, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(virtualoperatorsResource, "status", c.ns, virtualOperator), &v1alpha1.VirtualOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualOperator), err
}

// Delete takes name of the virtualOperator and deletes it. Returns an error if one occurs.
func (c *FakeVirtualOperators) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(virtualoperatorsResource, c.ns, name), &v1alpha1.VirtualOperator{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtualOperators) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(virtualoperatorsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.VirtualOperatorList{})
	return err
}

// Patch applies the patch and returns the patched virtualOperator.
func (c *FakeVirtualOperators) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VirtualOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(virtualoperatorsResource, c.ns, name, pt, data, subresources...), &v1alpha1.VirtualOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualOperator), err
}
