/*
Copyright 2021 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/openkruise/kruise/apis/public/v1alpha1"
	scheme "github.com/openkruise/kruise/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MetaInfosGetter has a method to return a MetaInfoInterface.
// A group's client should implement this interface.
type MetaInfosGetter interface {
	MetaInfos() MetaInfoInterface
}

// MetaInfoInterface has methods to work with MetaInfo resources.
type MetaInfoInterface interface {
	Create(*v1alpha1.MetaInfo) (*v1alpha1.MetaInfo, error)
	Update(*v1alpha1.MetaInfo) (*v1alpha1.MetaInfo, error)
	UpdateStatus(*v1alpha1.MetaInfo) (*v1alpha1.MetaInfo, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.MetaInfo, error)
	List(opts v1.ListOptions) (*v1alpha1.MetaInfoList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MetaInfo, err error)
	MetaInfoExpansion
}

// metaInfos implements MetaInfoInterface
type metaInfos struct {
	client rest.Interface
}

// newMetaInfos returns a MetaInfos
func newMetaInfos(c *PublicV1alpha1Client) *metaInfos {
	return &metaInfos{
		client: c.RESTClient(),
	}
}

// Get takes name of the metaInfo, and returns the corresponding metaInfo object, and an error if there is any.
func (c *metaInfos) Get(name string, options v1.GetOptions) (result *v1alpha1.MetaInfo, err error) {
	result = &v1alpha1.MetaInfo{}
	err = c.client.Get().
		Resource("metainfos").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MetaInfos that match those selectors.
func (c *metaInfos) List(opts v1.ListOptions) (result *v1alpha1.MetaInfoList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MetaInfoList{}
	err = c.client.Get().
		Resource("metainfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested metaInfos.
func (c *metaInfos) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("metainfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a metaInfo and creates it.  Returns the server's representation of the metaInfo, and an error, if there is any.
func (c *metaInfos) Create(metaInfo *v1alpha1.MetaInfo) (result *v1alpha1.MetaInfo, err error) {
	result = &v1alpha1.MetaInfo{}
	err = c.client.Post().
		Resource("metainfos").
		Body(metaInfo).
		Do().
		Into(result)
	return
}

// Update takes the representation of a metaInfo and updates it. Returns the server's representation of the metaInfo, and an error, if there is any.
func (c *metaInfos) Update(metaInfo *v1alpha1.MetaInfo) (result *v1alpha1.MetaInfo, err error) {
	result = &v1alpha1.MetaInfo{}
	err = c.client.Put().
		Resource("metainfos").
		Name(metaInfo.Name).
		Body(metaInfo).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *metaInfos) UpdateStatus(metaInfo *v1alpha1.MetaInfo) (result *v1alpha1.MetaInfo, err error) {
	result = &v1alpha1.MetaInfo{}
	err = c.client.Put().
		Resource("metainfos").
		Name(metaInfo.Name).
		SubResource("status").
		Body(metaInfo).
		Do().
		Into(result)
	return
}

// Delete takes name of the metaInfo and deletes it. Returns an error if one occurs.
func (c *metaInfos) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("metainfos").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *metaInfos) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("metainfos").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched metaInfo.
func (c *metaInfos) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MetaInfo, err error) {
	result = &v1alpha1.MetaInfo{}
	err = c.client.Patch(pt).
		Resource("metainfos").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
