# permissions for end users to view metainfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metainfo-viewer-role
rules:
- apiGroups:
  - public.kruise.io
  resources:
  - metainfos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - public.kruise.io
  resources:
  - metainfos/status
  verbs:
  - get
