# permissions for end users to view virtualoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualoperator-viewer-role
rules:
- apiGroups:
  - ctrlmesh.kruise.io
  resources:
  - virtualoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ctrlmesh.kruise.io
  resources:
  - virtualoperators/status
  verbs:
  - get
