/*
Copyright 2021 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/openkruise/kruise/apis/public/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMetaInfos implements MetaInfoInterface
type FakeMetaInfos struct {
	Fake *FakePublicV1alpha1
}

var metainfosResource = schema.GroupVersionResource{Group: "public.kruise.io", Version: "v1alpha1", Resource: "metainfos"}

var metainfosKind = schema.GroupVersionKind{Group: "public.kruise.io", Version: "v1alpha1", Kind: "MetaInfo"}

// Get takes name of the metaInfo, and returns the corresponding metaInfo object, and an error if there is any.
func (c *FakeMetaInfos) Get(name string, options v1.GetOptions) (result *v1alpha1.MetaInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(metainfosResource, name), &v1alpha1.MetaInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetaInfo), err
}

// List takes label and field selectors, and returns the list of MetaInfos that match those selectors.
func (c *FakeMetaInfos) List(opts v1.ListOptions) (result *v1alpha1.MetaInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(metainfosResource, metainfosKind, opts), &v1alpha1.MetaInfoList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MetaInfoList{ListMeta: obj.(*v1alpha1.MetaInfoList).ListMeta}
	for _, item := range obj.(*v1alpha1.MetaInfoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested metaInfos.
func (c *FakeMetaInfos) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(metainfosResource, opts))
}

// Create takes the representation of a metaInfo and creates it.  Returns the server's representation of the metaInfo, and an error, if there is any.
func (c *FakeMetaInfos) Create(metaInfo *v1alpha1.MetaInfo) (result *v1alpha1.MetaInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(metainfosResource, metaInfo), &v1alpha1.MetaInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetaInfo), err
}

// Update takes the representation of a metaInfo and updates it. Returns the server's representation of the metaInfo, and an error, if there is any.
func (c *FakeMetaInfos) Update(metaInfo *v1alpha1.MetaInfo) (result *v1alpha1.MetaInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(metainfosResource, metaInfo), &v1alpha1.MetaInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetaInfo), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMetaInfos) UpdateStatus(metaInfo *v1alpha1.MetaInfo) (*v1alpha1.MetaInfo, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(metainfosResource, "status", metaInfo), &v1alpha1.MetaInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetaInfo), err
}

// Delete takes name of the metaInfo and deletes it. Returns an error if one occurs.
func (c *FakeMetaInfos) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(metainfosResource, name), &v1alpha1.MetaInfo{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMetaInfos) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(metainfosResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.MetaInfoList{})
	return err
}

// Patch applies the patch and returns the patched metaInfo.
func (c *FakeMetaInfos) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MetaInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(metainfosResource, name, pt, data, subresources...), &v1alpha1.MetaInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetaInfo), err
}
